### ISSUE TITLE
TLS encryption

### ISSUE THREAD

**Issue by LaudixGit** [khoih-prog/AsyncWebServer_ESP32_W5500#2]
### Is your feature request related to a problem? Please describe.

Would like to use TLS encryption 

### Describe the solution you'd like

Would like [Self Signed Certs](https://github.com/khoih-prog/ESP32_HTTPS_Server/tree/master/examples/WT32_ETH01/Self-Signed-Certificate) to work in this library

### Describe alternatives you've considered

I successfully use encryption in ESP32_HTTPS_Server but that library isn't 'native' async

### Additional context

I attempted to use the existing BeginSecure within this library but there is a compile error
![image](https://user-images.githubusercontent.com/58885245/205452983-a56d5411-4cc5-4e92-93cf-ab5033f8327b.png)
![image](https://user-images.githubusercontent.com/58885245/205453000-90cae465-4bdd-49a9-a118-5c162079c5ac.png)

**Comment by LaudixGit** [comment]
@khoih-prog Since you don't mention encryption in the feature list, and there aren't any examples, I suspect you already know the ASYNC_TCP_SSL_ENABLED is not complete yet.

I am just adding this request to show interest.  I would _rather_ the HTTPS_Server_Generic library include async than have this library updated.

**Comment by khoih-prog** [comment]
The **TLS/SSL** is not ready for all AsyncWebServer libraries. And I **don't have the plan to update in the near future.**

Certainly, any PR to add the feature is appreciated.

**Comment by khoih-prog** [comment]
Hi @LaudixGit 

> I'll try to make the new **HTTPS_Server_Generic** library to support many more powerful-enough boards, such as ESP32, ESP8266, Teensy, RP2040, etc.

Try the newly-published [**HTTPS_Server_Generic**](https://github.com/khoih-prog/HTTPS_Server_Generic) library, especially the [**Async-Server**](https://github.com/khoih-prog/HTTPS_Server_Generic/tree/main/examples/ESP32_W5500/Async-Server) example

---

#### Releases v1.2.0

1. Initial coding to port [esp32_https_server](https://github.com/fhessel/esp32_https_server) and [ESP32_HTTPS_Server](https://github.com/khoih-prog/ESP32_HTTPS_Server) to ESP32 boards, **WT32_ETH01**, (ESP32 + **LwIP W5500**) and (ESP32 + **LwIP ENC28J60**) Ethernet
2. Use `allman astyle` and restyle library.

---

### TO DO

 1. Fix bug. Add enhancement
 2. For ESP32, using `ESP_TLS` for future ESP-IDF v5.0 instead of to-be-deprecated `OpenSSL`
 4. Using [ArduinoJson](https://github.com/bblanchon/ArduinoJson) `v6` instead of `v5.13.5-`
 5. Add support to more powerful-enough boards using LwIP WiFi/Ethernet, such as  :
   - `ESP8266` 
   - `Portenta_H7` WiFi / Ethernet
   - `RP2040W` WiFi
   - `Teensy 4.1` QNEthernet
   - etc.
